import os
import aiohttp
import asyncio
import questionary

LANGUAGES = {
    "Afrikaans": "af", "Albanian": "sq", "Amharic": "am", "Arabic": "ar", "Armenian": "hy",
    "Assamese": "as", "Azerbaijani": "az", "Bashkir": "ba", "Basque": "eu", "Belarusian": "be",
    "Bengali": "bn", "Bosnian": "bs", "Breton": "br", "Bulgarian": "bg", "Burmese": "my",
    "Cantonese": "yue", "Catalan": "ca", "Chinese": "zh", "Croatian": "hr", "Czech": "cs",
    "Danish": "da", "Dutch": "nl", "English": "en", "Estonian": "et", "Faroese": "fo",
    "Finnish": "fi", "French": "fr", "Galician": "gl", "Georgian": "ka", "German": "de",
    "Greek": "el", "Gujarati": "gu", "Haitian Creole": "ht", "Hausa": "ha", "Hawaiian": "haw",
    "Hebrew": "he", "Hindi": "hi", "Hungarian": "hu", "Icelandic": "is", "Indonesian": "id",
    "Italian": "it", "Japanese": "ja", "Javanese": "jv", "Kannada": "kn", "Kazakh": "kk",
    "Khmer": "km", "Korean": "ko", "Lao": "lo", "Latin": "la", "Latvian": "lv",
    "Lingala": "ln", "Lithuanian": "lt", "Luxembourgish": "lb", "Macedonian": "mk", "Malagasy": "mg",
    "Malay": "ms", "Malayalam": "ml", "Maltese": "mt", "Maori": "mi", "Marathi": "mr",
    "Mongolian": "mn", "Nepali": "ne", "Norwegian": "no", "Norwegian Nynorsk": "nn", "Occitan": "oc",
    "Pashto": "ps", "Persian": "fa", "Polish": "pl", "Portuguese": "pt", "Punjabi": "pa",
    "Romanian": "ro", "Russian": "ru", "Sanskrit": "sa", "Serbian": "sr", "Shona": "sn",
    "Sindhi": "sd", "Sinhala": "si", "Slovak": "sk", "Slovenian": "sl", "Somali": "so",
    "Spanish": "es", "Sundanese": "su", "Swahili": "sw", "Swedish": "sv", "Tagalog": "tl",
    "Tajik": "tg", "Tamil": "ta", "Tatar": "tt", "Telugu": "te", "Thai": "th",
    "Tibetan": "bo", "Turkish": "tr", "Turkmen": "tk", "Ukrainian": "uk", "Urdu": "ur",
    "Uzbek": "uz", "Vietnamese": "vi", "Welsh": "cy", "Yiddish": "yi", "Yoruba": "yo"
}

def create_env_file(config):
    env_content = f"""# Auto-generated by configure.py
GROQ_API_KEY={config.get('api_key', '')}
DEBUG={str(config.get('debug', False)).lower()}
UI_LANGUAGE={config.get('ui_language', 'en')}
WHISPER_MODEL={config.get('whisper_model', 'whisper-large-v3')}
BOT_LANGUAGE={config.get('bot_language', 'ru')}
KEEP_CONTEXT_BETWEEN_RECORDINGS={str(config.get('keep_context', True)).lower()}
LLM_MODEL={config.get('llm_model', 'llama-3.3-70b-versatile')}
LLM_BASE_URL=https://api.groq.com/openai/v1/chat/completions
FIX_GRAMMAR_BY_DEFAULT={str(config.get('fix_grammar', False)).lower()}
"""
    with open(".env", "w") as f:
        f.write(env_content)
    print("\n✅ Successfully created/updated .env file!")

async def check_api_key_and_get_models(api_key):
    try:
        headers = {
            "Authorization": f"Bearer {api_key}",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
        }
        async with aiohttp.ClientSession() as session:
            async with session.get(
                "https://api.groq.com/openai/v1/models",
                headers=headers
            ) as resp:
                if resp.status in (401, 403):
                    return False, []
                if resp.status != 200:
                    return True, []

                data = await resp.json()
                models = [m['id'] for m in data.get('data', []) if 'whisper' not in m['id']]

                # Ensure the custom model from previous steps is included if user relies on OpenRouter locally
                if "openai/gpt-oss-120b" not in models:
                    models.append("openai/gpt-oss-120b")

                return True, sorted(models)
    except Exception:
        # Network error, etc.
        return True, []

custom_style = questionary.Style([
    ('qmark', 'fg:#5f87ff bold'),       # token in front of the question
    ('question', 'bold'),               # question text
    ('answer', 'fg:#00af00 bold'),      # submitted answer text behind the question
    ('pointer', 'fg:#00d7ff bold'),     # pointer used in select and checkbox prompts
    ('highlighted', 'fg:#00d7ff bold'), # pointed-at choice in select and checkbox prompts
    ('selected', 'fg:#00d7ff'),         # style for a selected item of a checkbox
    ('separator', 'fg:#cc5454'),        # separator in lists
    ('instruction', ''),                # user instructions for select, rawselect, checkbox
    ('text', ''),                       # plain text
    ('disabled', 'fg:#858585 italic')   # disabled choices for select and checkbox prompts
])

def main():
    from dotenv import load_dotenv
    load_dotenv()
    existing_key = os.environ.get("GROQ_API_KEY", "")

    print("🎙️ Welcome to the vowit configuration wizard!\n")

    while True:
        if existing_key:
            use_existing = questionary.confirm(
                "An existing GROQ_API_KEY was found. Use it? (Press Enter for Yes)",
                default=True,
                style=custom_style
            ).ask()
            if use_existing:
                api_key = existing_key
            else:
                api_key = questionary.password(
                    "Enter your Groq API Key (https://console.groq.com/keys):",
                    validate=lambda text: len(text) > 0 or "API key cannot be empty",
                    style=custom_style
                ).ask()
        else:
            api_key = questionary.password(
                "Enter your Groq API Key (https://console.groq.com/keys):",
                validate=lambda text: len(text) > 0 or "API key cannot be empty",
                style=custom_style
            ).ask()

        if not api_key:
            return

        print("⏳ Verifying API key and fetching models...")

        # We need a new event loop because prompt_toolkit leaves the default one in a running state
        # or otherwise interferes with asyncio.run(). Creating a fresh isolated loop solves the RuntimeError.
        loop = asyncio.new_event_loop()
        try:
            is_valid, fetched_models = loop.run_until_complete(check_api_key_and_get_models(api_key))
        finally:
            loop.close()

        if is_valid:
            print(f"✅ API key is valid! Successfully loaded {len(fetched_models)} text models.\n")
            break
        else:
            print("❌ Invalid API key. Please check your key and try again.\n")

    # Spoken language
    spoken_lang_name = questionary.autocomplete(
        "Which language will you speak? (Type to search, press Tab to autocomplete/select, then Enter)",
        choices=list(LANGUAGES.keys()),
        validate=lambda text: text in LANGUAGES or "Please select a valid language from the list",
        match_middle=False,
        style=custom_style
    ).ask()

    if not spoken_lang_name:
        return

    bot_language = LANGUAGES[spoken_lang_name]

    # UI Language logic based on spoken language
    if spoken_lang_name == "Russian":
        ui_choice = questionary.select(
            "Which language do you prefer for desktop notifications? (Default: English)",
            choices=["English (en)", "Russian (ru)"],
            default="English (en)",
            style=custom_style
        ).ask()
        ui_language = "ru" if "Russian" in ui_choice else "en"
    else:
        # Default UI to English for all other spoken languages,
        # since currently we only support en/ru UI strings.
        ui_language = "en"

    whisper_model = questionary.select(
        "Which Whisper model do you want to use? (Default: whisper-large-v3)",
        choices=[
            "whisper-large-v3 (Best overall)",
            "whisper-large-v3-turbo (Faster)"
        ],
        default="whisper-large-v3 (Best overall)",
        style=custom_style
    ).ask()
    whisper_model = whisper_model.split(" ")[0]

    if not fetched_models:
        fetched_models = [
            "llama-3.3-70b-versatile",
            "gemma2-9b-it",
            "mixtral-8x7b-32768",
            "openai/gpt-oss-120b"
        ]

    # Determine the safest default
    if "openai/gpt-oss-120b" in fetched_models:
        default_model = "openai/gpt-oss-120b"
    elif "llama-3.3-70b-versatile" in fetched_models:
        default_model = "llama-3.3-70b-versatile"
    else:
        default_model = fetched_models[0]

    llm_model = questionary.select(
        f"Which LLM do you want to use for the grammar fix feature? (Default: {default_model})",
        choices=fetched_models,
        default=default_model,
        style=custom_style
    ).ask()

    fix_grammar = questionary.confirm(
        "Enable LLM grammar correction by default for all recordings? [Default: No]",
        default=False,
        style=custom_style
    ).ask()

    keep_context = questionary.confirm(
        "Keep context between rapid recordings? (Recommended) [Default: Yes]",
        default=True,
        style=custom_style
    ).ask()

    debug_mode = questionary.confirm(
        "Enable debug logging? [Default: No]",
        default=False,
        style=custom_style
    ).ask()

    config = {
        "api_key": api_key,
        "debug": debug_mode,
        "ui_language": ui_language,
        "whisper_model": whisper_model,
        "bot_language": bot_language,
        "keep_context": keep_context,
        "llm_model": llm_model,
        "fix_grammar": fix_grammar
    }

    create_env_file(config)
    print("🎉 You are ready to go! Run the daemon using `python main.py &`")

if __name__ == "__main__":
    main()
