import os
import questionary

LANGUAGES = {
    "English": "en",
    "Russian": "ru",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Chinese": "zh",
    "Japanese": "ja",
    "Korean": "ko",
    "Italian": "it",
    "Portuguese": "pt",
    "Turkish": "tr",
    "Polish": "pl",
    "Ukrainian": "uk",
    "Arabic": "ar"
}

def create_env_file(config):
    env_content = f"""# Auto-generated by configure.py
GROQ_API_KEY={config.get('api_key', '')}
DEBUG={str(config.get('debug', False)).lower()}
UI_LANGUAGE={config.get('ui_language', 'en')}
WHISPER_MODEL={config.get('whisper_model', 'whisper-large-v3')}
BOT_LANGUAGE={config.get('bot_language', 'ru')}
KEEP_CONTEXT_BETWEEN_RECORDINGS={str(config.get('keep_context', True)).lower()}
LLM_MODEL={config.get('llm_model', 'openai/gpt-oss-120b')}
LLM_BASE_URL=https://api.groq.com/openai/v1/chat/completions
"""
    with open(".env", "w") as f:
        f.write(env_content)
    print("\n✅ Successfully created/updated .env file!")

def main():
    print("🎙️ Welcome to the vowit configuration wizard!\n")

    api_key = questionary.password(
        "Enter your Groq API Key (https://console.groq.com/keys):",
        validate=lambda text: len(text) > 0 or "API key cannot be empty"
    ).ask()

    if not api_key:
        return

    # Spoken language
    spoken_lang_name = questionary.autocomplete(
        "Which language will you speak? (Type to search)",
        choices=list(LANGUAGES.keys()),
        validate=lambda text: text in LANGUAGES or "Please select a valid language from the list"
    ).ask()

    if not spoken_lang_name:
        return

    bot_language = LANGUAGES[spoken_lang_name]

    # UI Language logic based on spoken language
    if spoken_lang_name == "Russian":
        ui_choice = questionary.select(
            "Which language do you prefer for desktop notifications?",
            choices=["Russian (ru)", "English (en)"]
        ).ask()
        ui_language = "ru" if "Russian" in ui_choice else "en"
    else:
        # Default UI to English for all other spoken languages,
        # since currently we only support en/ru UI strings.
        ui_language = "en"

    whisper_model = questionary.select(
        "Which Whisper model do you want to use?",
        choices=[
            "whisper-large-v3 (Best overall)",
            "whisper-large-v3-turbo (Faster)",
            "distil-whisper-large-v3-en (English only, fastest)"
        ]
    ).ask()
    whisper_model = whisper_model.split(" ")[0]

    llm_model = questionary.select(
        "Which LLM do you want to use for the grammar fix feature?",
        choices=[
            "llama-3.3-70b-versatile",
            "gemma2-9b-it",
            "mixtral-8x7b-32768",
            "openai/gpt-oss-120b"
        ],
        default="openai/gpt-oss-120b"
    ).ask()

    keep_context = questionary.confirm(
        "Keep context between rapid recordings? (Recommended)",
        default=True
    ).ask()

    debug_mode = questionary.confirm(
        "Enable debug logging?",
        default=False
    ).ask()

    config = {
        "api_key": api_key,
        "debug": debug_mode,
        "ui_language": ui_language,
        "whisper_model": whisper_model,
        "bot_language": bot_language,
        "keep_context": keep_context,
        "llm_model": llm_model
    }

    create_env_file(config)
    print("🎉 You are ready to go! Run the daemon using `python main.py &`")

if __name__ == "__main__":
    main()
